name: Deploy Built Site to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Change to your preferred Node.js version

      - name: Install Dependencies and Build
        working-directory: fox-game
        run: |
          npm install
          parcel build src/index.html --public-url ./ --no-source-maps

      - name: Deploy site to gh-pages branch
        uses: crazy-max/ghaction-github-pages@v1.4.0
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        with:
          build_dir: dist # Change this to the directory where your built output is located

