name: Deploy Built Site to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: npm install and build
        working-directory: dist
        run: |
          npm install
          npm run build -- --public-url /project-files-for-fox-game/
      - name: Deploy site to gh-pages branch
        uses: crazy-max/ghaction-github-pages@v1.4.0
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        with:
          build_dir: dist
