name: Deploy Built Site to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.2' # Change to the latest LTS version of Node.js

      - name: Install Dependencies
        run: npm install

      - name: Build with Parcel
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.MY_PAT_TOKEN }}
        run: |
          npx gh-pages --dist dist --dotfiles --message "Deploy via GitHub Actions"








